const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');

const converter = require('../convert-dnaera.js');
const mapping = require('../mapping/getbased-dnaera-map.json');

const sampleInput = fs.readFileSync(path.join(__dirname, '..', 'samples', 'dnaera-mini.txt'), 'utf8');

test('parseArgs derives default output path and respects flags', () => {
  const parsed = converter.parseArgs(['samples/input.txt', '--mapping', 'mapping/custom.json']);
  assert.equal(parsed.inputPath, 'samples/input.txt');
  assert.equal(parsed.outputPath, 'samples/input.23andme.txt');
  assert.equal(parsed.mappingPath, 'mapping/custom.json');
  assert.equal(parsed.stdout, false);

  const stdoutParsed = converter.parseArgs(['samples/input.txt', '--stdout']);
  assert.equal(stdoutParsed.stdout, true);
  assert.equal(stdoutParsed.outputPath, null);
});

test('parseArgs rejects unexpected extra arguments', () => {
  assert.throws(
    () => converter.parseArgs(['input.txt', 'output.txt', 'extra.txt']),
    /Unexpected argument: extra\.txt/
  );
});

test('parseCsvLine handles quoted commas and escaped quotes', () => {
  assert.deepEqual(
    converter.parseCsvLine('alpha,"beta,gamma","delta ""quoted"""'),
    ['alpha', 'beta,gamma', 'delta "quoted"']
  );
});

test('toCsvLine escapes commas and quotes', () => {
  assert.equal(
    converter.toCsvLine(['alpha', 'beta,gamma', 'delta "quoted"']),
    'alpha,"beta,gamma","delta ""quoted"""'
  );
});

test('normalizers handle whitespace and chromosome prefixes', () => {
  assert.equal(converter.normalizeAllele(' a '), 'A');
  assert.equal(converter.normalizeChromosome('chr19'), '19');
  assert.equal(converter.normalizeChromosome(' mt '), 'MT');
});

test('chromosomeSortValue orders numeric and special chromosomes', () => {
  assert.equal(converter.chromosomeSortValue('1'), 1);
  assert.equal(converter.chromosomeSortValue('X'), 23);
  assert.equal(converter.chromosomeSortValue('MT'), 26);
  assert.equal(converter.chromosomeSortValue('weird'), 100);
});

test('parseDNAEraFile extracts metadata and rows', () => {
  const parsed = converter.parseDNAEraFile(sampleInput);
  assert.equal(parsed.metadata['GSGT Version'], '2.0.5');
  assert.equal(parsed.metadata.Content, 'GSAMD-24v3-0-EA_20034606_A1.bpm');
  assert.equal(parsed.rows.length, 11);
  assert.equal(parsed.rows[0]['SNP Name'], '1:103380393');
  assert.match(parsed.metadataLines[0], /^GSGT Version/);
});

test('resolveRsid handles name, GSA alias, direct rs and coordinate fallback', () => {
  assert.deepEqual(
    converter.resolveRsid({ 'SNP Name': 'rs1801133', Chr: '1', Position: '11856378' }, mapping),
    { rsid: 'rs1801133', mode: 'name', key: 'rs1801133' }
  );
  assert.deepEqual(
    converter.resolveRsid({ 'SNP Name': 'GSA-rs234706', Chr: '21', Position: '44485350' }, mapping),
    { rsid: 'rs234706', mode: 'name', key: 'GSA-rs234706' }
  );
  assert.deepEqual(
    converter.resolveRsid({ 'SNP Name': 'GSA-rs601338', Chr: '19', Position: '49206674' }, mapping),
    { rsid: 'rs601338', mode: 'name', key: 'rs601338' }
  );
  assert.deepEqual(
    converter.resolveRsid({ 'SNP Name': '19:45411941', Chr: '19', Position: '45411941' }, mapping),
    { rsid: 'rs429358', mode: 'coord', key: '19:45411941' }
  );
  assert.equal(
    converter.resolveRsid({ 'SNP Name': '1:110229816_CNV_GSTM1', Chr: '1', Position: '110229816' }, mapping),
    null
  );
});

test('buildOutput emits 23andMe-style text and tracks stats', () => {
  const parsed = converter.parseDNAEraFile(sampleInput);
  const result = converter.buildOutput(parsed, mapping);

  assert.match(result.text, /generated by 23andMe/);
  assert.match(result.text, /Original content: GSAMD-24v3-0-EA_20034606_A1\.bpm/);
  assert.match(result.text, /^rsid\tchromosome\tposition\tgenotype/m);
  assert.equal(result.matchedEntries.length, 8);
  assert.equal(result.stats.directName, 4);
  assert.equal(result.stats.coordinateFallback, 4);
  assert.equal(result.stats.skippedNoCall, 1);
  assert.equal(result.stats.skippedUnmapped, 2);
  assert.ok(result.missingTargets.includes('rs8175347'));
  assert.deepEqual(
    result.matchedEntries.map(entry => entry.rsid),
    ['rs1801133', 'rs953413', 'rs1800562', 'rs1799941', 'rs429358', 'rs7412', 'rs601338', 'rs234706']
  );
});

test('buildFilteredInputSubset keeps original DNAEra shape for relevant rows', () => {
  const parsed = converter.parseDNAEraFile(sampleInput);
  const filtered = converter.buildFilteredInputSubset(parsed, mapping);

  assert.equal(filtered.relevantRows.length, 8);
  assert.match(filtered.text, /^\[Header\]/);
  assert.match(filtered.text, /^Sample Name,SNP Name,Chr,Position,Allele1 - Plus,Allele2 - Plus$/m);
  assert.match(filtered.text, /^41220311706341,19:45411941,19,45411941,T,C$/m);
  assert.match(filtered.text, /^41220311706341,19:49206674,19,49206674,G,A$/m);
  assert.doesNotMatch(filtered.text, /^41220311706341,1:110229816_CNV_GSTM1,1,110229816,-,-$/m);
  assert.ok(filtered.text.includes('[Header]\nGSGT Version,2.0.5'));
});

test('deriveFilteredOutputPath uses input file stem', () => {
  assert.equal(
    converter.deriveFilteredOutputPath('/tmp/DNAEra-orig-41220311706341.csv'),
    '/tmp/DNAEra-orig-41220311706341-filtered-target-snps.csv'
  );
  assert.equal(
    converter.deriveFilteredOutputPath('/tmp/DNAEra-orig-41220311706341'),
    '/tmp/DNAEra-orig-41220311706341-filtered-target-snps.csv'
  );
});

test('deriveValidationPromptPaths use input file stem', () => {
  assert.equal(
    converter.deriveValidationPrompt1Path('/tmp/DNAEra-orig-41220311706341.csv'),
    '/tmp/DNAEra-orig-41220311706341-validation-prompt-1.md'
  );
  assert.equal(
    converter.deriveValidationPrompt2Path('/tmp/DNAEra-orig-41220311706341.csv'),
    '/tmp/DNAEra-orig-41220311706341-validation-prompt-2.md'
  );
});

test('buildOutput prefers direct name matches over coordinate fallback and records conflicts', () => {
  const parsed = {
    metadata: {},
    metadataLines: [],
    rows: [
      { 'SNP Name': '19:45411941', Chr: '19', Position: '45411941', 'Allele1 - Plus': 'T', 'Allele2 - Plus': 'C' },
      { 'SNP Name': 'rs429358', Chr: '19', Position: '45411941', 'Allele1 - Plus': 'C', 'Allele2 - Plus': 'C' },
      { 'SNP Name': 'rs429358', Chr: '19', Position: '45411941', 'Allele1 - Plus': 'T', 'Allele2 - Plus': 'T' }
    ]
  };

  const result = converter.buildOutput(parsed, mapping);
  assert.equal(result.matchedEntries.length, 1);
  assert.equal(result.matchedEntries[0].genotype, 'CC');
  assert.equal(result.stats.coordinateFallback, 1);
  assert.equal(result.stats.conflicts.length, 1);
  assert.match(result.stats.conflicts[0], /rs429358: kept CC/);
});

test('buildOutput skips unmapped rows and rows with invalid coordinates', () => {
  const parsed = {
    metadata: {},
    metadataLines: [],
    rows: [
      { 'SNP Name': 'unmapped-probe', Chr: '1', Position: '123', 'Allele1 - Plus': 'A', 'Allele2 - Plus': 'G' },
      { 'SNP Name': 'rs1801133', Chr: '', Position: '11856378', 'Allele1 - Plus': 'G', 'Allele2 - Plus': 'A' },
      { 'SNP Name': 'rs1801131', Chr: '1', Position: 'NaN', 'Allele1 - Plus': 'T', 'Allele2 - Plus': 'T' }
    ]
  };

  const result = converter.buildOutput(parsed, mapping);
  assert.equal(result.matchedEntries.length, 0);
  assert.equal(result.stats.skippedUnmapped, 3);
});

test('buildValidationPrompt1 and buildValidationPrompt2 render actual file content', () => {
  const parsed = converter.parseDNAEraFile(sampleInput);
  const output = converter.buildOutput(parsed, mapping);
  const filtered = converter.buildFilteredInputSubset(parsed, mapping);

  const prompt1 = converter.buildValidationPrompt1(filtered.text, '/tmp/example-filtered-target-snps.csv');
  const prompt2 = converter.buildValidationPrompt2(output.text, '/tmp/example-converted-23andme.txt');

  assert.match(prompt1, /Source file: `\/tmp\/example-filtered-target-snps\.csv`/);
  assert.match(prompt1, /Filtered DNAEra source subset:/);
  assert.match(prompt1, /^```text$/m);
  assert.match(prompt1, /^41220311706341,rs1801133,1,11856378,G,A$/m);

  assert.match(prompt2, /Converted file: `\/tmp\/example-converted-23andme\.txt`/);
  assert.match(prompt2, /Converted 23andMe-style file:/);
  assert.match(prompt2, /^rs429358\t19\t45411941\tTC$/m);
});

test('CLI writes stdout output for sample fixture', () => {
  const scriptPath = path.join(__dirname, '..', 'convert-dnaera.js');
  const samplePath = path.join(__dirname, '..', 'samples', 'dnaera-mini.txt');
  const result = spawnSync(process.execPath, [scriptPath, samplePath, '--stdout'], { encoding: 'utf8' });

  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /^# This data file generated by 23andMe at:/);
  assert.match(result.stdout, /^rsid\tchromosome\tposition\tgenotype/m);
  assert.match(result.stderr, /Converted 8 target SNPs to stdout/);
});

test('CLI writes output file and help exits successfully', () => {
  const scriptPath = path.join(__dirname, '..', 'convert-dnaera.js');
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'dnaera-to-23andme-'));
  const samplePath = path.join(tempDir, 'dnaera-mini.txt');
  fs.writeFileSync(samplePath, sampleInput, 'utf8');
  const outputPath = path.join(tempDir, 'output.txt');
  const filteredPath = path.join(tempDir, 'dnaera-mini-filtered-target-snps.csv');
  const prompt1Path = path.join(tempDir, 'dnaera-mini-validation-prompt-1.md');
  const prompt2Path = path.join(tempDir, 'dnaera-mini-validation-prompt-2.md');

  const writeResult = spawnSync(process.execPath, [scriptPath, samplePath, outputPath], { encoding: 'utf8' });
  assert.equal(writeResult.status, 0, writeResult.stderr);
  assert.equal(fs.existsSync(outputPath), true);
  assert.equal(fs.existsSync(filteredPath), true);
  assert.equal(fs.existsSync(prompt1Path), true);
  assert.equal(fs.existsSync(prompt2Path), true);
  const written = fs.readFileSync(outputPath, 'utf8');
  const filteredWritten = fs.readFileSync(filteredPath, 'utf8');
  const prompt1Written = fs.readFileSync(prompt1Path, 'utf8');
  const prompt2Written = fs.readFileSync(prompt2Path, 'utf8');
  assert.match(written, /rs429358\t19\t45411941\tTC/);
  assert.match(filteredWritten, /^\[Data\]/m);
  assert.doesNotMatch(filteredWritten, /Filtered Rows,/);
  assert.match(filteredWritten, /^41220311706341,rs7412,19,45412079,C,C$/m);
  assert.match(filteredWritten, /^41220311706341,19:49206674,19,49206674,G,A$/m);
  assert.match(prompt1Written, /Filtered DNAEra source subset:/);
  assert.match(prompt1Written, /^41220311706341,rs7412,19,45412079,C,C$/m);
  assert.match(prompt2Written, /Converted 23andMe-style file:/);
  assert.match(prompt2Written, /^rs429358\t19\t45411941\tTC$/m);
  assert.match(writeResult.stderr, /Filtered source rows written: 8 to/);
  assert.match(writeResult.stderr, /Validation prompt 1 written:/);
  assert.match(writeResult.stderr, /Validation prompt 2 written:/);

  const helpResult = spawnSync(process.execPath, [scriptPath, '--help'], { encoding: 'utf8' });
  assert.equal(helpResult.status, 0);
  assert.match(helpResult.stdout, /node convert-dnaera\.js <input> \[output\]/);
});

test('CLI exits non-zero on invalid arguments', () => {
  const scriptPath = path.join(__dirname, '..', 'convert-dnaera.js');
  const result = spawnSync(process.execPath, [scriptPath, 'a', 'b', 'c'], { encoding: 'utf8' });

  assert.equal(result.status, 1);
  assert.match(result.stderr, /Unexpected argument: c/);
});

test('CLI exits with usage when no input path is provided', () => {
  const scriptPath = path.join(__dirname, '..', 'convert-dnaera.js');
  const result = spawnSync(process.execPath, [scriptPath], { encoding: 'utf8' });

  assert.equal(result.status, 1);
  assert.match(result.stdout, /Usage:/);
});

test('CLI reports conflicts when duplicate loci disagree', () => {
  const scriptPath = path.join(__dirname, '..', 'convert-dnaera.js');
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'dnaera-to-23andme-conflict-'));
  const inputPath = path.join(tempDir, 'conflict.txt');
  fs.writeFileSync(
    inputPath,
    [
      '[Header]',
      'Content,,GSAMD-24v3-0-EA_20034606_A1.bpm',
      '[Data]',
      'Sample Name,SNP Name,Chr,Position,Allele1 - Plus,Allele2 - Plus',
      '1,19:45411941,19,45411941,T,C',
      '1,rs429358,19,45411941,C,C',
      '1,rs429358,19,45411941,T,T'
    ].join('\n'),
    'utf8'
  );

  const result = spawnSync(process.execPath, [scriptPath, inputPath, '--stdout'], { encoding: 'utf8' });
  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stderr, /Conflicts \(1\):/);
  assert.match(result.stderr, /kept CC from rs429358/);
});
